import Head from "next/head";

import { CaseStudyFiltered } from "@/types/queries/caseStudy";

import styles from "@/styles/pages/Home/Home.module.scss";

import { getFilteredCaseStudies } from "lib/caseStudiesQueries";

import ContentSection from "@/components/pages/home/HomeContentSection";

import useLocale from "lib/useLocale";
import fr from "@/locales/pages/case-studies/fr";
import en from "@/locales/pages/case-studies/en";

const CaseStudies = ({ caseStudies }: { caseStudies: CaseStudyFiltered[] }) => {
  const t = useLocale(fr, en);

  return (
    <>
      <Head>
        <title>Casestudies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} min-h-screen relative scroll-smooth`}>
        <section className="my-36 w-full fccc">
          <h1 className="font-bold text-main text-center text-5xl">
            {t.hero.title}
          </h1>
        </section>
        <ContentSection caseStudies={caseStudies} />
      </main>
    </>
  );
};

export default CaseStudies;

export async function getStaticProps({ locale }: { locale: string }) {
  const caseStudies = await getFilteredCaseStudies(locale, 100);

  return {
    props: { caseStudies },
  };
}
