import Head from "next/head";

import { CaseStudyHome } from "@/types/queries/caseStudy";

import styles from "@/styles/pages/Home/Home.module.scss";

import { getHomeCaseStudies } from "lib/caseStudiesQueries";

import HomeHero from "@/components/pages/home/HomeHero";
import ContentSection from "@/components/pages/home/HomeContentSection";

const Home = ({ caseStudies }: { caseStudies: CaseStudyHome[] }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} min-h-screen relative scroll-smooth`}>
        <HomeHero />
        <ContentSection caseStudies={caseStudies} />
      </main>
    </>
  );
};

export default Home;

export async function getStaticProps({ locale }: { locale: string }) {
  const caseStudies = await getHomeCaseStudies(locale);

  return {
    props: { caseStudies },
  };
}
