import Head from "next/head";

import { CaseStudyFiltered } from "@/types/queries/caseStudy";

import styles from "@/styles/pages/Home/Home.module.scss";

import { getFilteredCaseStudies } from "lib/caseStudiesQueries";

import HomeHero from "@/components/pages/home/HomeHero";
import ContentSection from "@/components/pages/home/HomeContentSection";
import { Asset } from "@/types/queries/asset";

const Home = ({ caseStudies }: { caseStudies: CaseStudyFiltered[] }) => {
  return (
    <>
      <Head>
        <title>Klara's Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} min-h-screen relative scroll-smooth`}>
        <HomeHero />
        <ContentSection caseStudies={caseStudies} />
      </main>
    </>
  );
};

export default Home;

export async function getStaticProps({ locale }: { locale: string }) {
  const caseStudies = await getFilteredCaseStudies(locale, 4);

  return {
    props: { caseStudies },
  };
}
