import type { NextPage } from "next";
import Head from "next/head";

import { Post } from "@/types/queries/posts";

import styles from "@/styles/pages/Home/Home.module.scss";

import HeroSection from "@/components/pages/home/HeroSection";
import ContentSection from "@/components/pages/home/ContentSection";
import ContactSection from "@/components/pages/home/ContactSection";

import client from "apollo-client";
import POSTS_QUERY from "queries/posts";

const Home: NextPage = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} min-h-screen relative`}>
        <HeroSection />
        <ContentSection posts={posts} />
        <ContactSection />
      </main>
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const { data } = await client.query({ query: POSTS_QUERY });

  let posts = data.posts.data || [];

  return {
    props: { posts },
  };
}
